### ISSUE TITLE
SP totals

### ISSUE THREAD

**Issue by cseverson** [PrometheusSatyen/Cerebral#16]
Just started using. When looking at my character in game. it shows an SP total that is 275,000 less then what the program is showing. It shows I have an extractor available but cannot extract due to not having the 5.5m SP.

looks like the toons that have in the SP farm (recently used accelerators on) are all about 275,000 SP more on the app than in-game.

**Comment by ficti0n1** [comment]
This could be a monolith issue. It doesn't update total SP until a skill finishes. I know your writing about SP showing as higher though. I think this is still a monolith issue though and it struggling with accelerated characters.

**Comment by PrometheusSatyen** [comment]
In-game, pause and unpause your skill queue.

Then close and reopen your character sheet and compare the total SP to the app's total SP.
