### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by poundjd** [PrometheusSatyen/Cerebral#24]
I am sure that I am not the Only one with multiple EVE-online Accounts, Id like to manage them all in one location--here.
I also understand that all of the accounts will have to have used real-world $$, and I can understand CCP's position on this.

**Comment by PrometheusSatyen** [comment]
You can manage all your EVE accounts in Cerebral. The account you use to create the developer application does not matter, simply authorize the rest of your characters in the same way you did the first.
